# 头部菜单，title: link
menu:
  Whoami: /whoami
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github: https://github.com/mrgaodi

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # https://cdn.jsdelivr.net/gh/mrgaodi/CDN/img/img-001.jpg

# 默认文章封面图
cover: https://cdn.jsdelivr.net/gh/mrgaodi/CDN/img/img-002.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '82e4646b42761428bdc5'
    # 应用秘钥
    clientSecret: 'f3c1963d2ce3c608bb9cf91cb8bad064c1e66f09'
    # issue仓库名
    repo: 'mrgaodi.github.io'
    # Github名
    owner: 'mrgaodi'
    # Github名
    admin: ['mrgaodi']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: GaoDi

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: https://cdn.jsdelivr.net/gh/mrgaodi/CDN/img/favicon.png

# 网站logo
logo: https://cdn.jsdelivr.net/gh/mrgaodi/CDN/img/logo.png

# rss文件
rss: atom.xml
